Homework 3. Task 3. Волков Александр
volkov-alexander-d/spbu_2020_kotlin_homeworks pull request #11
Opened 2021-03-23 01:24 UTC by volkov-alexander-d

2021-03-23 14:49 UTC, cupertank requested changes

2021-03-23 14:49 UTC, cupertank commented on build.gradle.kts
> +    implementation("org.junit.jupiter:junit-jupiter")
это должно быть testImplementation

2021-03-23 14:49 UTC, cupertank commented on src/main/kotlin/homework_3/task_3.kt
> +    var functionNames: List<FunctionName>
Мне кажется, что все эти значения не должны быть var

2021-03-23 14:49 UTC, cupertank commented on src/main/kotlin/homework_3/task_3.kt
> +}
Разделение неплохое, но стоит объединить это в какой-то класс плюс сделать половину функций private, чтобы юзер просто скрамливал путь конфиг, а на выходе получал файл или текст на котлине

2021-03-23 14:49 UTC, cupertank commented on src/test/kotlin/homework_3/Task_3KtTest.kt
> +                generateFileForTests("src/test/resources/testСonfigs/testconfig1.yaml").toString()
Во-первых мне не нравится работа с ресурсами, почитай как работать с ресурсами в котлине. Во-вторых ты можешь объединить вот эти файлы в одну подпапку и унифицировать названия файлов в подпапке, например config.yaml и expect.kt. Это позволит тебе в аргумент передавать название подпапки и упростить чтение. В-третьих унеси чтение и generateFileForTests в сам тест.

2021-03-29 15:27 UTC, cupertank requested changes

2021-03-29 15:27 UTC, cupertank commented on src/main/kotlin/homework_3/task_3.kt
> +        for (i in functionNames) {
Ну давай хотя бы `for (functionName in functionNames) {....`

2021-03-29 15:27 UTC, cupertank commented on src/test/kotlin/homework_3/Task_3KtTest.kt
> +                .replace("\r", "")
Ну разбей это хоть немного на перменные....
Читать просто невозможно

2021-03-29 15:27 UTC, cupertank commented on src/main/kotlin/homework_1/Action.kt
> +import kotlinx.serialization.SerialName
Почему в сюда влетело вообще что-то из другого дз....
Будь внимательнее с ветками

2021-03-29 15:27 UTC, cupertank commented
Разрезолви ещё конфликты

2021-03-29 16:10 UTC, volkov-alexander-d commented on src/main/kotlin/homework_1/Action.kt
> +import kotlinx.serialization.SerialName
Это из ветки master
<img width="279" alt="14" src="https://user-images.githubusercontent.com/70965603/112866425-753e3b80-90c2-11eb-8734-cc107d49328e.png">

2021-04-01 12:59 UTC, cupertank approved these changes

2021-04-01 12:59 UTC, merged