Homework 6. Task 1. Волков Александр
volkov-alexander-d/spbu_2020_kotlin_homeworks pull request #16
Opened 2021-04-14 14:11 UTC by volkov-alexander-d

2021-04-20 04:00 UTC, elena-lyulina requested changes
Хочется иметь функцию сортировки, куда передаешь количество потоков + возможность на графике отрисовывать неограниченное количество функций с разным количеством потоков, а не 4 захардкоженных варианта

2021-04-20 04:15 UTC, elena-lyulina commented on src/main/kotlin/homework_6/drawPlot.kt
> +        }
создание массивов нужно вынести в отдельную функцию, еще лучше использовать Random(), чтобы сгенерировать рандомные массивы

2021-04-21 14:34 UTC, volkov-alexander-d commented
Про проблемы с detektом я в телеграме написал.

2021-04-22 14:30 UTC, elena-lyulina requested changes
уже лучше!

2021-04-22 14:30 UTC, elena-lyulina commented on src/main/kotlin/homework_6/mergeSort.kt
> +fun IntArray.binarySearch(value: Int, left: Int, right: Int): Int {
на это тоже хочется тесты, лучше отдельным классом

2021-04-22 14:30 UTC, elena-lyulina commented on src/main/kotlin/homework_6/mergeSort.kt
> +    numberOfThreads: Int = 1
вообще нерепрезантативные названия параметров, совершенно непонятно по ним, что происходит
переименуй, пожалуйста, и добавь комментариев, как вообще это работает и что означают параметры

2021-04-22 14:30 UTC, elena-lyulina commented on src/main/kotlin/homework_6/mergeSort.kt
> +    numberOfThreads: Int = 1
то же самое про функцию ниже

2021-04-22 14:30 UTC, elena-lyulina commented on src/main/kotlin/homework_6/mergeSort.kt
> +    resultArray: IntArray,
Попробуй обойтись без resultArray, странно, что ты вызываешь сортировку в IntArray, а в итоге сортируется не он, а результат оказывается в каком-то другом массиве, так не должно быть

2021-04-22 14:30 UTC, elena-lyulina commented on src/main/kotlin/homework_6/mergeSort.kt
> +    resultArray: IntArray,
то же самое про функцию ниже

2021-04-22 14:30 UTC, elena-lyulina commented on src/main/kotlin/homework_6/mergeSort.kt
> +    numberOfThreads: Int = 1
и это же относится к параметрам типа n1, n2
о чем это? непонятно

2021-04-22 14:30 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1.kt
> +    val scanner = java.util.Scanner(System.`in`)
уже неплохо, но хочется вот такого, как я тебе писала в предыдущем ревью:

> возможность на графике отрисовывать неограниченное количество функций с разным количеством потоков

имелось в виду, что у тебя на одном графике появляется несколько функций, соответствующих разным потокам, чтобы можно было сравнивать их между собой по времени и элементам, что-то вроде такого 
![image](https://user-images.githubusercontent.com/24303332/115731913-2ff2ee00-a390-11eb-9926-e19dbf38d8a5.png)

2021-04-23 13:33 UTC, volkov-alexander-d commented on src/test/kotlin/homework_6/MergeSortKtTest.kt
> +                assert(expectedList == actualArray.toList())
Для массивов equals не очень удобный, он не сравнивает содержание.

2021-05-03 11:47 UTC, elena-lyulina commented on src/test/kotlin/homework_6/MergeSortKtTest.kt
> +                assert(expectedList == actualArray.toList())
можно использовать assertArrayEquals

2021-05-03 11:47 UTC, elena-lyulina commented on src/test/kotlin/homework_6/MergeSortKtTest.kt
> +                assert(expectedList == actualArray.toList())
так что поправь, пожалуйста, сейчас странно выглядит весь этот перевод типов туда-сюда

2021-05-03 12:14 UTC, elena-lyulina requested changes
почти!

2021-05-03 12:14 UTC, elena-lyulina commented on src/main/kotlin/homework_6/task_1.kt
>  package homework_6
этот файл тоже не по стайл гайду называется :(
я понимаю, что у тебя уже во всех заданиях так, и это не очень хорошо
давай ты этот файл переименуешь тут, чтобы я уже зачла задачу, а в отдельной ветке (чтобы это не смешивать с этой задачей) переименуешь все остальные файлы по стайлгайду и сделаешь на меня реквест, будем все делать красиво

2021-05-03 12:14 UTC, elena-lyulina commented on src/test/kotlin/homework_6/MergeSortKtTest.kt
> +                    list.add(Arguments.of(List(arraySize) { it }, getRandomArray(arraySize), numberOfThreads))
тут не сразу очевидно, что происходит, на первый взгляд выглядит, что ты передаешь в аргументы какой-то рандомный массив, совсем не связанный с твоим только что созданным и отсортированным, и только почитав реализацию, понимаешь, что происходит

вообще ты можешь просто создавать рандомный массив (через Random, а не шаффл), а уже в тестах сортировать его с помощью встроенной сортировки и сравнивать результат с твоей многопоточной версией

2021-05-04 18:40 UTC, elena-lyulina requested changes
последний раз, обещаю :)

2021-05-04 18:40 UTC, elena-lyulina commented on src/main/kotlin/homework_6/MergeSort.kt
>          leftBound3: Int,
а что за leftBound3? название неочевидное

2021-05-13 13:27 UTC, elena-lyulina approved these changes
Класс

2021-05-13 13:28 UTC, merged