Homework 8. Task 1. Волков Александр
volkov-alexander-d/spbu_2020_kotlin_homeworks pull request #17
Opened 2021-04-16 10:49 UTC by volkov-alexander-d

2021-04-16 13:20 UTC, volkov-alexander-d commented
Теперь уже работает, но выглядит все равно плохо.

2021-04-23 14:43 UTC, SpirinEgor approved these changes
![Screenshot 2021-04-23 at 17 42 05](https://user-images.githubusercontent.com/22539802/115888124-3b5f1b80-a45b-11eb-8759-85928d68bebf.png)
Что-то явно не то с кодировкой...

Получилось хорошо. Саму домашку продолжай в этой же ветке делать

2021-04-23 14:43 UTC, SpirinEgor commented on src/main/kotlin/homework_8/TicTacToe.kt
> +const val SIZE = 3
Такое надо в companion object выносить, а не хранить глобально

2021-04-23 14:43 UTC, SpirinEgor commented on src/main/kotlin/homework_8/TicTacToe.kt
> +class GameController : Controller() {
Очень много логики в контроллере, надо куда-то отдельно в модель вынести. Она при добавлении ботов будет только увеличиваться. Класс слишком большим станет

2021-04-23 14:43 UTC, SpirinEgor commented on src/main/kotlin/homework_8/TicTacToe.kt
> +class GameView : View("Tic Tac Toe") {
Ну и View можно тоже куда-то в отдельный файл вынести, чтобы совсем по красоте.

2021-05-19 00:50 UTC, volkov-alexander-d commented
Для запуска мультиплеера нужно два раза запустить TicTacToe.kt, предварительно запустив GameServer.kt, и выбрать "Play with other player"

2021-05-24 10:22 UTC, SpirinEgor requested changes
Почему-то при игре с самим собой или ботом вылетает при окончании игры. Ругается на сокеты, но это странно, мне для такой игры сервер не нужен. Ну и не забывай, что пользователи не любят большое окно со здоровенной ошибкой :( Серверная часть работает хорошо, нравится. Однако сообщения "First player won" не очень понятны, я бы все-таки писал крестик или нолик.

По логике -- не получилось разнести все по MVС паттерну. Большая часть логики все еще лежит в контроллере, хотя он отвечает за связующее звено просто. Немного копипасты из другой реализации, кажется у тебя тоже отлично ляжет такой подход.

1. Сделать абстрактный класс модели. Там будет какая-то общая логика и абстрактный метод move (ну или по-своему назови)
2. Несколько наследников такого класса. PlayWithYouselfModel -- move просто ставит по переданным координатам нужный символ (не забудь про Enum). PlayWithBotModel -- инициализируется сложностью, а метод move принимает координаты, ставит значок и сразу же делает ход бота. Для ботов ты уже придумал хорошую абстракцию.
3. Если будет сетевой режим, то это еще одна реализация модели. Только в ней после хода игрока ты начинаешь слушать сокет в ожидании хода другого игрока.
4. Теперь в контроллере, ты как и раньше опрашиваешь игрока, как он хочет играть. По вызову start, контроллер просто создает нужную модель с заданными параметрами.

2021-05-24 10:22 UTC, SpirinEgor commented on src/main/kotlin/homework_8/GameClient.kt
> +        const val ZERO_CODE = '0'.toInt()
Это просто 0 :)

2021-05-24 10:22 UTC, SpirinEgor commented on src/main/kotlin/homework_8/GameController.kt
> +    lateinit var socket: DefaultClientWebSocketSession
Кажется, что клиент должны создаваться только при игре онлайн. И это точно не часть контроллера. Это отдельная модель, которая отвечает за онлайн игру.

2021-05-24 10:22 UTC, SpirinEgor commented on src/main/kotlin/homework_8/GameController.kt
> +        model.activateBot()
Слишком много if и наплетенной логики. Фактически одна функция и следит за онлайн игрой, и делает ход бота. Эта вся логика должна быть разнесена по разным моделям. А сам контроллер дергает абстрактный `move` и ничего не знает о процессах за ним.

2021-05-24 10:22 UTC, SpirinEgor commented on src/main/kotlin/homework_8/GameController.kt
> +            button.text("X")
Все эти X и 0 лучше в Enum вынести. Вдруг я захочу в квадратики-нолики играть. Придется по всему коду бегать...

2021-05-24 10:22 UTC, SpirinEgor commented on src/main/kotlin/homework_8/GameController.kt
> +    private suspend fun multiplayerMove(row: Int, column: Int) {
И это не тут.

2021-05-24 10:22 UTC, SpirinEgor commented on src/main/kotlin/homework_8/model/Bot.kt
> +        }
Вот тут можно все сделать в разы аккуратнее, если бы getWinner возвращал бы Enum класс. Не было бы вот таких стычек по переводу из инта в строку.

2021-05-27 11:54 UTC, nbirillo requested changes

2021-05-27 11:54 UTC, nbirillo commented on src/main/kotlin/homework_8/GameServer.kt
> +                if (connections.size > 2) {
А что если меньше 2 коннекшенов?

2021-05-27 11:54 UTC, nbirillo commented on src/main/kotlin/homework_8/GameClient.kt
> +        const val SYMBOL_START = "symbol:"
Может стоит использовать эту константу в GameServer при отправке? а то поменяется она потом, а там не поменяется. То же про символы

2021-05-27 11:54 UTC, nbirillo commented on src/main/kotlin/homework_8/GameClient.kt
> +            client.webSocket(method = HttpMethod.Get, host = "127.0.0.1", port = 8080, path = "/") {
Константы типа хоста и порта обычно выносят в конфиг

2021-05-27 11:54 UTC, nbirillo commented on src/main/kotlin/homework_8/GameClient.kt
> +        if (playersSymbol == '0') {
Лучше всегда такие сравнения с переменными проводить

2021-05-27 11:54 UTC, nbirillo commented on src/main/kotlin/homework_8/GameClient.kt
> +        val moveText = text.replace(MOVE_START, "")
Может ты сделаешь функцию для парсинга текста, которая будет возвращать какой-нибудь инстантс датакласса с нужными полями и тогда будет понятно что там парсится, из чего текст состоит и тд?

2021-05-27 23:37 UTC, volkov-alexander-d commented on src/main/kotlin/homework_8/GameServer.kt
> +                if (connections.size > 2) {
Тогда он просто добавит новое соединение к connections, а если их наберется два, то уже начнет игру.

2021-05-29 16:43 UTC, SpirinEgor requested changes
Архитектурно ты тут закопался, кажется уже адекватно не разгрести это :) Но мы и не проходили пока такое. Поправь стилистические штуки и комментарии Насти

2021-05-29 16:43 UTC, SpirinEgor commented on src/main/kotlin/homework_8/GameController.kt
> +    }
Выглядит стремно. Я вроде бы уже писал, что не очень хорошо модель и контроллер мешать. Но тут базовый when уже сделает функцию более аккуратной

2021-05-29 16:43 UTC, SpirinEgor commented on src/main/kotlin/homework_8/model/Bot.kt
> +class RandomBot(model: OnePlayerModel) : Bot(model) {
Кажется должна быть обратная связь. Игра знает про текущих игроков. А не игроки про игру. Ну то есть что тут мешает потенциально боту закрыть сразу все ячейки?)

2021-05-29 16:43 UTC, SpirinEgor commented on src/main/kotlin/homework_8/model/FieldsChecker.kt
> +object FieldsChecker {
Нет нужды создавать object. Если ты хочешь сделать ряд функций, объединенный логикой, то просто положи в файл с нужным названием.
В джаве необходимо создавать классы, но в котлине можно и без этого обойтись.

2021-06-04 09:16 UTC, SpirinEgor approved these changes
Получилось круто, даже адекватно сущности в итоге разграничил

2021-06-04 12:32 UTC, nbirillo commented on src/main/kotlin/homework_8/GameClient.kt
> +    }
Вот эат функция выглядит совсем костыльно. А все остальное мне нравится, молодец!

2021-06-04 12:38 UTC, nbirillo approved these changes
В остальном все окей, поэтому зачтено (с небольшим штрафом за ту функцию)

2021-06-04 12:39 UTC, merged