Homework 7. Task 1. Волков Александр
volkov-alexander-d/spbu_2020_kotlin_homeworks pull request #18
Opened 2021-04-21 17:00 UTC by volkov-alexander-d

2021-04-21 17:10 UTC, volkov-alexander-d commented
Здесь очень много повторяющегося кода, я удалю его после мержа homework_6.1

2021-04-22 14:32 UTC, elena-lyulina commented
> Здесь очень много повторяющегося кода, я удалю его после мержа homework_6.1

Давай сначала смержим 6.1, а то там еще много изменений будет. Тем более дедлайн по 7.1 сейчас подвинулся

2021-05-31 19:03 UTC, elena-lyulina requested changes

2021-05-31 19:03 UTC, elena-lyulina commented on src/main/kotlin/homework_6/DrawPlot.kt
> +class DrawPlot(numbersOfThreadsOrCoroutines: List<Int>, maxNumberOfElements: Int, step: Int, isForMT: Boolean) {
штуки типа "threads" или "coroutines", которые ты используешь ниже как подписи на графике можно тоже записать в свойство класса, и в дальнейшем просто вызывать его

2021-06-02 09:40 UTC, volkov-alexander-d commented
Пришлось использовать Suppress("LongParameterList"), чтобы не было повторяющихся кусков кода

2021-06-03 11:50 UTC, elena-lyulina requested changes

2021-06-03 11:50 UTC, elena-lyulina commented on src/main/kotlin/homework_6/MergeSorter.kt
> +        numberOfThreadsForRightPart: Int
последний шаг: понять, что тебе на самом деле не надо передавать сюда кучу параметров. тебе можно передать только два параметра: что будет запускаться на правом потоке и на левом потоке (или корутинах), типа такого:
abstract fun launchParallel(runOnLeft: () -> Unit, runOnRight: () -> Unit)

и соответственно внутри merge ты просто будешь передавать туда лямбды, а реализация этого метода может быть такая:

```
    override fun IntArray.launchParallelMerge(runOnLeft: () -> Unit, runOnRight: () -> Unit) {
        runBlocking {
            launch {
                runOnLeft()
            }
            launch {
                runOnRight()
            }
        }
    }
```

2021-06-03 11:50 UTC, elena-lyulina commented on src/main/kotlin/homework_6/MergeSorter.kt
> +        numberOfThreadsForRightPart: Int
соответственно тебе не нужны теперь обе функции launchParallelMerge и launchParallelSort, так как они будут одинаковые

2021-06-03 11:50 UTC, elena-lyulina commented on src/main/kotlin/homework_6/MergeSorter.kt
> +        numberOfThreadsForRightPart: Int
ну и от supress тоже можно избавиться

2021-06-03 11:50 UTC, elena-lyulina commented on src/main/kotlin/homework_6/MergeSorter.kt
> +class MultiThreadMergeSorter : MergeSorter() {
вынеси AsyncMergeSorter и MultiThreadMergeSorter в разные файлы, пожалуйста, так будет чуть легче читать код

2021-06-03 11:50 UTC, elena-lyulina commented on src/main/kotlin/homework_6/MergeSorter.kt
> +class MultiThreadMergeSorter : MergeSorter() {
а еще их можно сделать объектами

2021-06-03 11:50 UTC, elena-lyulina commented on src/test/kotlin/homework_6/MergeSortKtTest.kt
> +                for (arraySize in 0..99) {
а почему такой маленький размер массива в тестах? давай хотя бы несколько тысяч

2021-06-03 22:16 UTC, elena-lyulina approved these changes
хорошо :)

2021-06-03 22:16 UTC, merged