Homework 7. Task 2. Волков Александр
volkov-alexander-d/spbu_2020_kotlin_homeworks pull request #19
Opened 2021-04-22 20:38 UTC by volkov-alexander-d

2021-05-13 14:49 UTC, elena-lyulina requested changes

2021-05-13 14:49 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +        var string = ""
строки нехорошо складывать в циклах, они неизменяемые и поэтому у тебя при каждом изменении создается новая строка на самом деле, что может оч плохо отразиться на производительности в больших циклах, например
это можно избежать, используя StringBuilder, например, который специально для этого придуман
но в твоем случае обрати внимание на joinToString, туда можно передавать разделители и все такое

2021-05-13 14:49 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +                        ]
тут прямо очень некрасиво смотрится форматирование и сложно все это читать, более того, кажется, что надо к j прибавлять startColumn, а не startRow (как вообще тесты проходят?), и есть вероятность, что ты допустил ошибку как раз из-за сложночитаемой реализации
как это поправить? например, можно итерировать одновременно по двум range:
`for ((i1, i2) in (rowRange).zip(secondMatrix.rowRange)) { .. }`
и тогда можно будет вызывать просто `this.mainMatrix[i1, j1] += secondMatrix.mainMatrix[i2, j2]` (заметить, что ты можешь опустить array опять же для читаемости)

для этого надо завести свойство rowRange (и сolRange вдобавок), ну и поправить во всех остальных местах

2021-05-13 14:49 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +                secondMatrix.numberOfColumns == 1 -> {
если у второй матрицы всего одна колонка, то мы не можем просто у нее вызывать oneColumnMatrixMultiply? зачем нам еще один метод?

2021-05-13 14:49 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +                this.numberOfRows == 1 -> {
а не надо это проверить и у второй матрицы тоже?

2021-05-13 14:49 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +            return arrayOf(firstListOfSubMatrices.toTypedArray(), secondListOfSubMatrices.toTypedArray())
мб тут лучше обойтись без создания списков и переводов их потом в массивы, а просто создания четырех сабматриц и из них уже составить arrayOf(arrayOf(matrix1, matrix2), arrayOf(matrix3, matrix4)), смотрится чуть компактнее

2021-05-13 14:49 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +                    listOfCoroutines.forEach { it.join() }
а это никак нельзя сделать в цикле по индексам? а то смотрится пугающе

2021-05-13 14:49 UTC, elena-lyulina commented on src/test/kotlin/homework_7/MatrixTest.kt
> +    companion object {
класс, но еще хочется тестов с отрицательными числами и нулями

2021-05-13 14:49 UTC, elena-lyulina commented
о, и поправь конфликты, пожалуйста

2021-05-13 15:21 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +    override operator fun equals(other: Any?): Boolean = this.toString() == other.toString()
а еще такая реализация чуть странная, вдруг с toString что-то случится, логичнее сразу сравнивать массивы

2021-05-13 15:28 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +                    listOfCoroutines.forEach { it.join() }
ты можешь внутри coroutineScope не вызывать join, так как выход из скопа произойдет только тогда, когда все корутины закончат свою работу

2021-05-13 15:29 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +            launch {
для этого отдельную корутину странно заводить, можно просто вызвать умножение

2021-05-17 09:39 UTC, volkov-alexander-d commented on src/main/kotlin/homework_7/Matrix.kt
> +    }
<img width="455" alt="29" src="https://user-images.githubusercontent.com/70965603/118468001-fb631f80-b70c-11eb-879b-25fb6c8fd67d.png">

2021-05-17 09:53 UTC, volkov-alexander-d commented on src/main/kotlin/homework_7/Matrix.kt
> +                secondMatrix.numberOfColumns == 1 -> {
Метод oneColumnMatrixMultiply предназначен для случая, когда у левой матрицы всего один столбец. Его нельзя применять к правой матрице, так как умножение некоммутативное.

2021-05-17 09:54 UTC, volkov-alexander-d commented on src/main/kotlin/homework_7/Matrix.kt
> +                this.numberOfRows == 1 -> {
Нет, там алгоритм не зависит от второй матрицы.

2021-05-28 13:56 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +    constructor(array: Array<IntArray>) : this(array.size, array[0].size) {
конструктор должен идти после свойств, companion object вообще должен быть внизу, перечитай пожалуйста еще раз https://kotlinlang.org/docs/coding-conventions.html#class-layout

2021-05-28 14:21 UTC, elena-lyulina requested changes
ух, как-то все еще очень громоздко смотрится, давай ты поправишь пока эти комменты, тогда некоторые функции сразу сильно уменьшатся в размере и станут читабельнее и потом уже надо смотреть, как еще это можно все аккуратнее написать

потому что вот это конечно пугает 
![image](https://user-images.githubusercontent.com/24303332/119998146-1a00ca80-bfd9-11eb-8807-e83269d87818.png)

2021-05-28 14:21 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +    override operator fun equals(other: Any?): Boolean {
contentEquals?

2021-05-28 14:21 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +        return listOfRows.joinToString("\n")
постарайся это одной строчкой написать

2021-05-28 14:21 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +                for ((column1, column2) in columnRange.zip(secondMatrix.columnRange)) {
а что тебе мешает так же сделать в остальных местах как я просила? у тебя все еще куча мест, где ты пишешь нечитаемые выражения типа
` resultMatrix.mainMatrix[resultMatrix.startRow, resultMatrix.startColumn + column2 - secondMatrix.startColumn                    ]`

2021-05-28 19:04 UTC, volkov-alexander-d commented on src/main/kotlin/homework_7/Matrix.kt
> +    constructor(array: Array<IntArray>) : this(array.size, array[0].size) {
Теперь вроде правильно

2021-05-31 18:44 UTC, elena-lyulina requested changes

2021-05-31 18:44 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +            val secondMatrixRowRange = columnRange.map { it - startColumn + secondMatrix.startRow }
ты же можешь просто брать secondMatrix.columnRange и тд прям внутри zip (в других местах аналогично)

2021-05-31 18:44 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +                for ((secondMatrixColumn, resultMatrixColumn) in secondMatrix.columnRange.zip(resultMatrixColumnRange))
придерживайся, пожалуйста, одного стиля именования 
например, у тебя в методе plusAssign имена row1, column1, а тут secondMatrixRow, secondMatrixColumn 

в качестве итерируемой переменной в цикле лучше использовать более короткие и лаконичные переменные

2021-05-31 18:44 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +                for ((secondMatrixColumn, resultMatrixColumn) in secondMatrix.columnRange.zip(resultMatrixColumnRange))
это если что комментарий ко всем остальным методам тоже, где аналогичная ситуация

2021-05-31 18:44 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +    }
init идет после свойств https://kotlinlang.org/docs/coding-conventions.html#class-layout

2021-05-31 18:44 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +                        }
класс, что это уже происходит в цикле, но:
1. с первого раза непонятно, откуда взялись 0..1, лучше явно итерироваться по размерам твоих массивов, чтобы случайно не выйти за границу массивов
2. названия итерируемых переменных с трудом передают, что происходит, а так же откуда взялись 1 и 0 в launch { ... }

2021-05-31 18:44 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +            fun recursiveLaunch(
название recursiveLaunch не передает, что именно ты рекурсивно запускаешь

2021-06-01 15:40 UTC, volkov-alexander-d commented on src/main/kotlin/homework_7/Matrix.kt
> +            val secondMatrixRowRange = columnRange.map { it - startColumn + secondMatrix.startRow }
Ну я это скорее для читабельности делал

2021-06-01 15:51 UTC, volkov-alexander-d commented on src/main/kotlin/homework_7/Matrix.kt
> +    }
Я подумал, что раз они идут одним пунктом, то допустим такой порядок

2021-06-01 16:46 UTC, volkov-alexander-d commented on src/main/kotlin/homework_7/Matrix.kt
> +                        }
Теперь у каждой переменной видно, по какому множеству она проходит, а для нуля и единицы я сделал константы с понятными названиями.

2021-06-01 17:19 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +            val secondMatrixRowRange = columnRange.map { it - startColumn + secondMatrix.startRow }
странная читабельность получилось, ты просто по сути заново зачем-то посчитал range :)
и ты все еще это не поправил, не считай пожалуйста заново range, используй свойство, у тебя у каждой матрицы есть columnRange и rowRange

2021-06-01 17:21 UTC, elena-lyulina commented on src/main/kotlin/homework_7/Matrix.kt
> +                        }
ух, ладно, допустим

2021-06-01 17:21 UTC, elena-lyulina requested changes
ты немного не так понял один комментарий, поправь его пожалуйста

2021-06-03 11:30 UTC, elena-lyulina approved these changes
ура :)

2021-06-03 11:30 UTC, merged