Homework 1. Task 3. Волков Александр
volkov-alexander-d/spbu_2020_kotlin_homeworks pull request #3
Opened 2021-02-25 14:26 UTC by volkov-alexander-d

2021-02-26 11:13 UTC, nbirillo requested changes
Давай ты поменяешь архитектуру и потом уже будем смотреть более детально, так как все поменяется. Еще небольшие комментарии общие: постарайся делать более понятные имена, когда ты видишь имена index1 и index2, это нечитаемо. Например в случае действия move это может быть _from_ и _to_. Это касается всех мест, включая main. Еще небольшой момент - если делать сущность Action и потом несколько сущностей для действий, то лучше сделать отдельную папку (ну или более умными словами package) _action_ и туда это все сложить
Если будут вопросы - пиши

2021-02-26 11:13 UTC, nbirillo commented on src/main/kotlin/firsthomework/PerformedCommandStorage.kt
> +    }
Об этом я сегодня говорила, для коротких функций лучше делать так:
```
private fun isEmpty(): Boolean = size == 0
```

2021-02-26 11:13 UTC, nbirillo commented on src/main/kotlin/firsthomework/PerformedCommandStorage.kt
> +    }
Ну и это станет проще, если будет просто список\очередь\стек

2021-02-26 11:13 UTC, nbirillo commented on src/main/kotlin/firsthomework/PerformedCommandStorage.kt
> +    fun pushFront(value: Int) {
Ну собственно вот так делать плохо, просто потому что это по идее же действие, а не то, что делает сам этот сторадж. Потому что, если тебе надо добавить еще экшенов ты тогда не будешь менять сторадж при успешной реализации, а просто добавишь новую сущность, которая наследуется от Action или чего-то такого и будешь тут использовать. Надеюсь понятна суть

2021-02-26 11:13 UTC, nbirillo commented on src/main/kotlin/firsthomework/PerformedCommandStorage.kt
> +            throw IndexOutOfBoundsException()
Кидать ошибки без сообщений плохо

2021-02-26 11:13 UTC, nbirillo commented on src/main/kotlin/firsthomework/PerformedCommandStorage.kt
> +            secondElement!!.changeValue(temporary)
Использовать !! плохо, как уже говорилось на лекции, используй ?. и элвис оператор например

2021-02-26 11:13 UTC, nbirillo commented on src/main/kotlin/firsthomework/task_3.kt
> +const val NUMBER4 = 4
Давай обойдемся без глобальных переменных

2021-02-26 16:20 UTC, volkov-alexander-d commented on src/main/kotlin/firsthomework/task_3.kt
> +const val NUMBER4 = 4
Если не выносить в качестве констант, то чек не проходит.

2021-03-01 12:35 UTC, nbirillo requested changes

2021-03-01 12:35 UTC, nbirillo commented on src/main/kotlin/firsthomework/Action.kt
> +fun ArrayDeque<Int>.moveElements(firstIndex: Int, secondIndex: Int) {
Возможно эту функцию стоит сделать доступной только здесь?

2021-03-01 12:35 UTC, nbirillo commented on src/main/kotlin/firsthomework/Action.kt
> +    }
Поменять местами значения в `a` и `b` можно так: `a = b.also { b = a }`

2021-03-01 12:35 UTC, nbirillo commented on src/main/kotlin/firsthomework/Action.kt
> +        this.add(second, temporary)
Вроде как в задании говорится, что нужно элемент с i позиции перенести на j-ую, то есть по сути просто вставить в нужное место, а элемент на j-ой просто сместится

2021-03-01 12:35 UTC, nbirillo commented on src/main/kotlin/firsthomework/Action.kt
> +        storage.getActions().addElement(this)
Если ты посмотришь внимательно, что у тебя везде повторяется эта строчка. Во всех действиях. Может быть стоит сделать метод у `PerformedCommandStorage`, который будет добавлять действие в сторадж? Просто стоит ли давать пользователю возможность напрямую лезть в сторадж к действиям?

2021-03-01 12:35 UTC, nbirillo commented on src/main/kotlin/firsthomework/Action.kt
> +        storage.getActions().removeLast()
То же самое про эту строчку. Но что касается ее, то вот тут как раз немного нарушаются принципы абстракции и кажется, что удалить действие лучше внутри самого стораджа. То есть действие должно просто удалить первый элемент, а удалить экшн я бы посоветовала внутри стораджа, чтобы не было так, что по каким-т о причинам получилось так, что удалилось не то действие. А так ты берешь действие внутри стораджа последнее (удаляя из последовательности действий) и после его отменяешь, а отмена уже у каждого своя.

2021-03-01 12:35 UTC, nbirillo commented on src/main/kotlin/firsthomework/Action.kt
> +        storage.getActions().removeLast()
Этот комментарий и про `addElement` относится ко всем действиям

2021-03-01 12:35 UTC, nbirillo commented on src/main/kotlin/firsthomework/PerformedCommandStorage.kt
> +    fun getActions() = actions
Так в котлине не пишут) посмотри про` get()` и `set()`

2021-03-01 12:35 UTC, nbirillo commented on src/main/kotlin/firsthomework/PerformedCommandStorage.kt
> +            actions.lastElement().undo()
Насколько я понимаю, `lastElement` только возвращает последний элемент, но не удаляет его из коллекции (а из undo удаление как раз надо вынести и оно уйдет сюда)

2021-03-01 12:35 UTC, nbirillo commented on src/main/kotlin/firsthomework/task_3.kt
> +const val NUMBER4 = 4
А зачем тебе вообще эти константы? можно просто написать эти значения в main, так как какого-то сильного смысла в них нет

2021-03-01 15:53 UTC, volkov-alexander-d commented on src/main/kotlin/firsthomework/task_3.kt
> +const val NUMBER4 = 4
Если в качестве констант не объявлять, то ругается на magic number

2021-03-01 18:50 UTC, nbirillo requested changes
Почти готово

2021-03-01 18:50 UTC, nbirillo commented on src/main/kotlin/firsthomework/Action.kt
> +    Action {
Очень странно, что детект на такое не ругается. Сделай вот так, пожалуйста:
```
) : Action {
```

Или так появится ошибка?

2021-03-01 18:50 UTC, nbirillo commented on src/main/kotlin/firsthomework/PerformedCommandStorage.kt
> +        println(this._arrayDeque.joinToString(" "))
А можешь сделать чуть лучше и печатать что-то разумное, если элементов нет?

2021-03-01 18:50 UTC, nbirillo commented on src/main/kotlin/firsthomework/task_3.kt
> +const val NUMBER4 = 4
ну окей, давай так оставим

2021-03-02 16:00 UTC, nbirillo approved these changes
Зачтено

2021-03-02 16:00 UTC, merged