new config
volkov-alexander-d/spbu_2020_kotlin_homeworks pull request #4
Opened 2021-02-28 21:34 UTC by volkov-alexander-d

2021-03-01 17:27 UTC, volkov-alexander-d commented
@nbirillo

2021-03-01 18:34 UTC, nbirillo requested changes

2021-03-01 18:34 UTC, nbirillo commented on config/detekt/detekt.yml
> +    packagePattern: '[a-z][A-Za-z0-9_]*'
А если там точка будет?

2021-03-02 15:57 UTC, nbirillo approved these changes

2021-03-02 15:57 UTC, merged