Homework 2. Task 3. Волков Александр
volkov-alexander-d/spbu_2020_kotlin_homeworks pull request #7
Opened 2021-03-11 00:06 UTC by volkov-alexander-d

2021-03-12 09:39 UTC, nbirillo requested changes

2021-03-12 09:39 UTC, nbirillo commented on src/main/kotlin/firsthomework/PerformedCommandStorage.kt
> +        val stringInJsonFormat = Json.encodeToString(temporaryList)
А зачем тебе temporaryList? почему не использовать actions сразу?

2021-03-12 09:39 UTC, nbirillo commented on src/main/kotlin/firsthomework/task_3.kt
> +    testStorage1.serialize("testfile.json")
Давай ты вынесешь имя файла в константу?

2021-03-12 09:39 UTC, nbirillo commented on src/main/kotlin/firsthomework/Action.kt
> +@Serializable
Посмотри в сторону `SerialName`, чтобы сохранять не с такими автоматическими именами как `firsthomework.MoveElement`, а чтобы например там не было приписки `firsthomework`

2021-03-22 10:41 UTC, elena-lyulina requested changes

2021-03-22 10:41 UTC, elena-lyulina commented on src/main/kotlin/firsthomework/task_3.kt
> +const val FILE_NAME = "testfile.json"
Немного про константы:
Не стоит делать глобальные константы, если они используются только в одном месте в одном файлы. Они были придуманы не для этого, а для реально глобальных констант, которые везде используются, например, ты хочешь число пи записать куда-то и везде использовать. Если же они используются только в одном месте, то и делать надо так, чтобы их было видно только в одном месте -- не надо их всем показывать (вспоминаем инкапсуляцию)

Да, я знаю, что detekt ругается, если их делать не константами. В общем случае действительно не должно быть магических чисел в коде, это [плохой](https://refactoring.guru/replace-magic-number-with-symbolic-constant) паттерн программирования. Но давай поймем, что у тебя сейчас немного другой случай -- ты используешь эти числа для своеобразного **тестирования**, того, что обычно не выносится в src main, а лежит в совсем другой папке и соответственно там немного другие правила. Тесты вы скоро начнете добавлять, и проблем с magic number у вас уже не будет, так как вы просто перестанете писать такой код в main. А пока предлагаю поставить на этот файл `@file:Suppress("MagicNumber")`, чтобы детект не ругался, с полным осознанием почему мы сейчас так можем сделать и почему только на этом файле (если оно к тебе еще не пришло, скажи, пожалуйста, постараюсь подробнее объяснить)

Вместо глобальных констант таких давай сделаем переменные внутри `fun main()`

2021-03-22 10:41 UTC, elena-lyulina commented on src/main/kotlin/firsthomework/task_3.kt
>  const val NUMBER3 = 3
меня немного убивает то, что у тебя есть пакеты firsthomework и homework_2, придерживайся, пожалуйста, одного стиля именования

2021-03-22 10:41 UTC, elena-lyulina commented on src/main/kotlin/firsthomework/task_3.kt
> +const val FILE_NAME = "testfile.json"
Пожалуйста, пусть файл будет сразу создаваться в ресурсах, в корне проекта ему нечего делать

2021-03-23 10:15 UTC, elena-lyulina requested changes
почти, еще немного и будет хорошо

2021-03-23 10:15 UTC, elena-lyulina commented on src/main/kotlin/homework_1/Action.kt
> +package homework_1
Ага, кто-то не читает стайлгайды https://kotlinlang.org/docs/coding-conventions.html#naming-rules

> Names of packages are always lowercase and do not use underscores

2021-03-23 10:15 UTC, elena-lyulina commented on src/main/kotlin/homework_1/task_3.kt
> +const val FILE_NAME = "src/main/resources/testfile.json"
вот этому тоже не надо быть константой, ты ведь нигде кроме этого файла ее не используешь

2021-03-23 10:15 UTC, elena-lyulina commented on src/main/kotlin/homework_1/task_3.kt
> +const val FILE_NAME = "src/main/resources/testfile.json"
ура, у нас появились ресурсы, но в них еще должна быть та же структура пакетов, что и в классе, в котором вы используете ресурсы

2021-03-24 09:55 UTC, elena-lyulina approved these changes
Это зачет

2021-03-24 09:56 UTC, merged