Homework 4. Task 2. Волков Александр
volkov-alexander-d/spbu_2020_kotlin_homeworks pull request #9
Opened 2021-03-18 18:01 UTC by volkov-alexander-d

2021-03-26 17:03 UTC, SpirinEgor requested changes

2021-03-26 17:03 UTC, SpirinEgor commented on src/main/kotlin/homework_4/AVLTree.kt
> +    }
И тут про =

2021-03-26 17:03 UTC, SpirinEgor commented on src/main/kotlin/homework_4/AVLTree.kt
> +class Entry<K, V>(override val key: K, override val value: V) : Map.Entry<K, V>
А AVLNode может быть этим самым Entry?

2021-03-26 17:03 UTC, SpirinEgor commented on src/main/kotlin/homework_4/task_2.kt
> +@file:Suppress("MagicNumber")
А здесь что надо заглушать?

2021-03-26 17:27 UTC, volkov-alexander-d commented on config/detekt/detekt.yml
> +    ignorePrivate: true
С AVLTree все нормально, он ругается на AVLNode.
<img width="495" alt="7" src="https://user-images.githubusercontent.com/70965603/112670258-bc81bd80-8e71-11eb-8797-24be2c1ab287.png">

2021-03-26 17:38 UTC, volkov-alexander-d commented on src/main/kotlin/homework_4/AVLNode.kt
> +class AVLNode<K : Comparable<K>, V>(private var key: K, private var pvalue: V) {
https://kotlinlang.org/docs/coding-conventions.html#names-for-backing-properties Просто надо с pvalue поменять на _value. А var потому что в remove в одном из случаев не создается новая вершина, а заменяются key и value в текущей.

2021-03-26 17:47 UTC, volkov-alexander-d commented on src/main/kotlin/homework_4/AVLNode.kt
> +    }
В таком случае не запустится
<img width="613" alt="8" src="https://user-images.githubusercontent.com/70965603/112672349-6eba8480-8e74-11eb-8b22-d5354ff688bd.png">
, хотя по сути код то же самое делает.

2021-03-26 18:13 UTC, volkov-alexander-d commented on src/main/kotlin/homework_4/AVLNode.kt
> +class AVLNode<K : Comparable<K>, V>(private var key: K, private var pvalue: V) {
Вспомнил, почему в первый раз pvalue назвал: 
<img width="466" alt="9" src="https://user-images.githubusercontent.com/70965603/112675356-1be2cc00-8e78-11eb-8ff4-ac51e1d0739b.png">

2021-03-26 18:19 UTC, volkov-alexander-d commented on src/main/kotlin/homework_4/task_2.kt
> +@file:Suppress("MagicNumber")
<img width="61" alt="10" src="https://user-images.githubusercontent.com/70965603/112675958-dffc3680-8e78-11eb-9f12-d09da97c59cf.png">

2021-03-26 18:31 UTC, volkov-alexander-d commented on src/main/kotlin/homework_4/AVLTree.kt
> +class Entry<K, V>(override val key: K, override val value: V) : Map.Entry<K, V>
Если Entry сделать родительским классом AVLNode, то придется сделать key и value публичными полями, а это нарушает инкапсуляцию.

2021-03-28 14:29 UTC, SpirinEgor commented on config/detekt/detekt.yml
> +    ignorePrivate: true
Ну значит надо как-то декомпозировать :) Он же не просто так тебе предлагает уменьшать число функций...

2021-03-28 14:32 UTC, SpirinEgor commented on src/main/kotlin/homework_4/AVLNode.kt
> +class AVLNode<K : Comparable<K>, V>(private var key: K, private var pvalue: V) {
Окей, с pvalue оставь, согласен.
Логика с заменой key, value мне не нравится. У тебя всё-таки при удалении меняется вершина целиком, то есть логичнее листовую вершину перенести.
А вообще, чем чаще стоит val, тем лучше. Во-первых это безопаснее для мультипоточности, а во-вторых поддерживает инвариант класса. Ты всегда уверен, что поместив вершину в дереву, её ключ не изменится и дерево будет корректным.

2021-03-28 14:33 UTC, SpirinEgor commented on src/main/kotlin/homework_4/AVLNode.kt
> +    }
Хмм, а это не проблема нейминга? Если приходящий value назвать по-другому, то всё равно проблема останется?

2021-03-28 14:34 UTC, SpirinEgor commented on src/main/kotlin/homework_4/AVLNode.kt
> +    }
Может скобки ещё добавить надо, там приоритет может не совсем очевидный быть

2021-03-28 14:35 UTC, SpirinEgor commented on src/main/kotlin/homework_4/AVLTree.kt
> +class Entry<K, V>(override val key: K, override val value: V) : Map.Entry<K, V>
Потому что надо делать трюк как с pvalue. То есть ключ и значение -- переменные с геттером, но без сеттера. На них можно взглянуть, но нельзя поменять.

2021-03-28 14:36 UTC, SpirinEgor commented on src/main/kotlin/homework_4/AVLTree.kt
> +class Entry<K, V>(override val key: K, override val value: V) : Map.Entry<K, V>
И к инкапсуляции это никак не относится :) Скорее всего ты путаешь с сокрытием реализации. Но ключ и значение вершины в дереве - это известный интерфейс, его скрывать нет смысла.

2021-03-28 14:36 UTC, SpirinEgor commented on src/main/kotlin/homework_4/AVLTree.kt
> +class Entry<K, V>(override val key: K, override val value: V) : Map.Entry<K, V>
Если это единственная проблема -- надо использовать Entry.

2021-03-28 14:43 UTC, SpirinEgor requested changes
Ответил на комментарии, если возникнут ещё вопросы -- быстрее всего в телеграмме написать :)
Также не заметил при первой проверке -- а где тесты? Столько функциональности и 0 проверок...

2021-03-28 14:43 UTC, SpirinEgor commented on src/main/kotlin/homework_4/task_2.kt
> +@file:Suppress("MagicNumber")
Ага, что-то сначала не заметил.
Вообще такой интерфейс -- максимальное не уважение к пользователю. Почему бы не использовать "add", "remove", ... чтобы было понятно и не надо делать инструкций.

Также решение через when не самое грамотное. Мы уже в мире ООП живём -- простенький интерфейс из nameCommand и appleyCommand и можно поддерживать список возможных действий. Но это уже не обязательно.

2021-03-28 15:58 UTC, volkov-alexander-d commented on src/main/kotlin/homework_4/AVLNode.kt
> +    }
Все равно проблема остается, даже если добавить скобки и переименовать.

2021-03-28 18:34 UTC, volkov-alexander-d commented on src/main/kotlin/homework_4/AVLNode.kt
> +    }
Оказалось, что при таком рекурсивном вызове обязательно указывать тип возвращаемого значения, тогда ошибка исчезает.

2021-03-29 11:38 UTC, SpirinEgor approved these changes

2021-03-29 11:38 UTC, merged